# Generated by Django 2.0.4 on 2018-04-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formlessness', '0002_auto_20180410_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='processing',
            name='recipient_email',
            field=models.CharField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
